let snakeLevel = [];
function levelCreation() {
  let string1 = "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww";
  let string2 = "w                                        w";
  let string3 = "w                                        w";
  let string4 = "w                                        w";
  let string5 = "w   f                                    w";
  let string6 = "w                                        w";
  let string7 = "w                                        w";
  let string8 = "w                                 f      w";
  let string9 = "w                                        w";
  let string10 = "w                                        w";
  let string11 = "w         f                              w";
  let string12 = "w                                        w";
  let string13 = "w                                        w";
  let string14 = "w                           f            w";
  let string15 = "w                                        w";
  let string16 = "w                                        w";
  let string17 = "w               f                        w";
  let string18 = "w                                        w";
  let string19 = "w                                        w";
  let string20 = "w                     f                  w";
  let string21 = "w                                        w";
  let string22 = "w                                        w";
  let string23 = "w                                        w";
  let string24 = "w                 f                      w";
  let string25 = "w                                        w";
  let string26 = "w                                        w";
  let string27 = "w                         f              w";
  let string28 = "w                                        w";
  let string29 = "w                                        w";
  let string30 = "w           f                            w";
  let string31 = "w                                        w";
  let string32 = "w                                        w";
  let string33 = "w                               f        w";
  let string34 = "w                                        w";
  let string35 = "w                                        w";
  let string36 = "w     f                                  w";
  let string37 = "w                                        w";
  let string38 = "w                                        w";
  let string39 = "w                                     f  w";
  let string40 = "w                                        w";
  let string41 = "w                                        w";
  let string42 = "wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww";
  snakeLevel.push(string1);
  snakeLevel.push(string2);
  snakeLevel.push(string3);
  snakeLevel.push(string4);
  snakeLevel.push(string5);
  snakeLevel.push(string6);
  snakeLevel.push(string7);
  snakeLevel.push(string8);
  snakeLevel.push(string9);
  snakeLevel.push(string10);
  snakeLevel.push(string11);
  snakeLevel.push(string12);
  snakeLevel.push(string13);
  snakeLevel.push(string14);
  snakeLevel.push(string15);
  snakeLevel.push(string16);
  snakeLevel.push(string17);
  snakeLevel.push(string18);
  snakeLevel.push(string19);
  snakeLevel.push(string20);
  snakeLevel.push(string21);
  snakeLevel.push(string22);
  snakeLevel.push(string23);
  snakeLevel.push(string24);
  snakeLevel.push(string25);
  snakeLevel.push(string26);
  snakeLevel.push(string27);
  snakeLevel.push(string28);
  snakeLevel.push(string29);
  snakeLevel.push(string30);
  snakeLevel.push(string31);
  snakeLevel.push(string32);
  snakeLevel.push(string33);
  snakeLevel.push(string34);
  snakeLevel.push(string35);
  snakeLevel.push(string36);
  snakeLevel.push(string37);
  snakeLevel.push(string38);
  snakeLevel.push(string39);
  snakeLevel.push(string40);
  snakeLevel.push(string41);
  snakeLevel.push(string42);
}

module.exports = levelCreation;